version: "3.8"
services:
  mongodb:
    container_name: mongo-service
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"
    command: >
      bash -c "
      mongod --bind_ip_all & 
      sleep 5 && 
      mongoimport --db wanderlust --collection posts --file /data/sample_posts.json --jsonArray &&
      tail -f /dev/null"

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "31100:8080"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"

  redis:
    container_name: redis-service
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
        - 6379
    depends_on:
      - mongodb

volumes:
  data:
